name: Validate RaceDay Part 1

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check required folders
        run: |
          test -d docs
          test -d .github/workflows

      - name: Check required Part 1 files
        run: |
          test -f docs/RaceDay_ERD.png
          test -f docs/RaceDay_API_Endpoint_Plan.md
          test -f docs/RaceDay_Database.sql
          test -f README.md

      - name: Check SQL file is not empty
        run: |
          test -s docs/RaceDay_Database.sql

      - name: Check API plan is not empty
        run: |
          test -s docs/RaceDay_API_Endpoint_Plan.md

      - name: Validation successful
        run: echo "RaceDay Part 1 validation passed successfully."
